#!/usr/bin/python3

def get_info(name):
    for version in bible_versions:
        if name == version[0]:
            return version[1], version[2]
    return "", ""
    
bible_versions = [
    ("AB", "The Apostles' Bible", ""),
    ("ABP", "Apostolic Bible Polyglot English Text", ""),
    ("ACV", "A Conservative Version", ""),
    ("AKJV", "American King James Version", ""),
    ("ASV", "American Standard Version -1901", ""),
    ("Anderson", "Henry Tompkins Anderson's 1864 New Testament", ""),
    ("BBE", "1949/1964 Bible in Basic English", ""),
    ("BWE", "Bible in Worldwide English", ""),
    ("CPDV", "Catholic Public Domain Version", ""),
    ("Common", "The Common Edition: New Testament", ""),
    ("DRC", "Douay-Rheims Bible, Challoner Revision", ""),
    ("Darby", "Darby Bible -1889", ""),
    ("EMTV", "English Majority Text Version, 2012 Edition with Greek Explanatory Notes", ""),
    ("Etheridge", "The Peschito Syriac New Testament: Translated into English by John Wesley Etheridge", ""),
    ("Geneva1599", "Geneva Bible -1599", ""),
    ("Godbey", "1902 William Baxter Godbey NT", ""),
    ("GodsWord", "GOD'S WORD to the Nations", ""),
    ("ISV", "International Standard Version", ""),
    ("JPS", "Jewish Publication Society Old Testament", ""),
    ("Jubilee2000", "English Jubilee 2000 Bible", ""),
    ("KJV", "King James Version -1769 with Strongs Numbers and Morphology", ""),
    ("KJVA", "King James Version -1769 including Apocrypha, with Strongs Numbers and Morphology", ""),
    ("KJVPCE", "King James Version: Pure Cambridge Edition", ""),
    ("LEB", "The Lexham English Bible", ""),
    ("LITV", "Green's Literal Translation", ""),
    ("LO", "The Living Oracles NT", ""),
    ("Leeser", "1853 Leeser Old Testament", ""),
    ("MKJV", "Green's Modern King James Version", ""),
    ("Montgomery", "Montgomery New Testament", ""),
    ("Murdock", "James Murdock's Translation of the Syriac Peshitta", ""),
    ("NETfree", "Free version of New English Translation with limited notes", ""),
    ("NETtext", "New English Translation text only with footnote markers", ""),
    ("NHEB", "New Heart English Bible", ""),
    ("NHEBJE", "New Heart English Bible: Jehovah Edition", ""),
    ("NHEBME", "New Heart English Bible: Messianic Edition", ""),
    ("Noyes", "1869 Noyes Translation", ""),
    ("OEB", "Open English Bible (US Spelling)", ""),
    ("OEBcth", "Open English Bible (Commonwealth Spelling)", ""),
    ("OrthJBC", "The Orthodox Jewish Brit Chadasha", ""),
    ("RKJNT", "Revised King James New Testament", ""),
    ("RNKJV", "Restored Name King James Version", ""),
    ("RWebster", "Revised Webster Version -1833", ""),
    ("Rotherham", "The Emphasised Bible by J. B. Rotherham", ""),
    ("SPE", "Samaritan Pentateuch in English", ""),
    ("Twenty", "Twentieth Century New Testament", ""),
    ("Tyndale", "William Tyndale Bible (1525/1530)", ""),
    ("UKJV", "Updated King James Version", ""),
    ("WEB", "World English Bible", ""),
    ("WEBBE", "World English Bible: British Edition", ""),
    ("WEBME", "World English Bible: Messianic Edition", ""),
    ("Webster", "Webster Bible", ""),
    ("Weymouth", "Weymouth NT -1912", ""),
    ("Worsley", "1770 John Worsley NT", ""),
    ("YLT", "Young's Literal Translation -1898", ""),    
]
