#!/bin/bash
export SWORD_PATH=$(pwd)/tmp
mkdir tmp

unzip ../source/sword_modules/en/AB.zip -d tmp/ && mod2osis AB > tmp/AB.xml
unzip ../source/sword_modules/en/ABP.zip -d tmp/ && mod2osis ABP > tmp/ABP.xml
unzip ../source/sword_modules/en/ACV.zip -d tmp/ && mod2osis ACV > tmp/ACV.xml
unzip ../source/sword_modules/en/AKJV.zip -d tmp/ && mod2osis AKJV > tmp/AKJV.xml
unzip ../source/sword_modules/en/ASV.zip -d tmp/ && mod2osis ASV > tmp/ASV.xml
unzip ../source/sword_modules/en/Anderson.zip -d tmp/ && mod2osis Anderson > tmp/Anderson.xml
unzip ../source/sword_modules/en/BBE.zip -d tmp/ && mod2osis BBE > tmp/BBE.xml
unzip ../source/sword_modules/en/BWE.zip -d tmp/ && mod2osis BWE > tmp/BWE.xml
unzip ../source/sword_modules/en/CPDV.zip -d tmp/ && mod2osis CPDV > tmp/CPDV.xml
unzip ../source/sword_modules/en/Common.zip -d tmp/ && mod2osis Common > tmp/Common.xml
unzip ../source/sword_modules/en/DRC.zip -d tmp/ && mod2osis DRC > tmp/DRC.xml
unzip ../source/sword_modules/en/Darby.zip -d tmp/ && mod2osis Darby > tmp/Darby.xml
unzip ../source/sword_modules/en/EMTV.zip -d tmp/ && mod2osis EMTV > tmp/EMTV.xml
unzip ../source/sword_modules/en/Etheridge.zip -d tmp/ && mod2osis Etheridge > tmp/Etheridge.xml
unzip ../source/sword_modules/en/Geneva1599.zip -d tmp/ && mod2osis Geneva1599 > tmp/Geneva1599.xml
unzip ../source/sword_modules/en/Godbey.zip -d tmp/ && mod2osis Godbey > tmp/Godbey.xml
unzip ../source/sword_modules/en/GodsWord.zip -d tmp/ && mod2osis GodsWord > tmp/GodsWord.xml
unzip ../source/sword_modules/en/ISV.zip -d tmp/ && mod2osis ISV > tmp/ISV.xml
unzip ../source/sword_modules/en/JPS.zip -d tmp/ && mod2osis JPS > tmp/JPS.xml
unzip ../source/sword_modules/en/Jubilee2000.zip -d tmp/ && mod2osis Jubilee2000 > tmp/Jubilee2000.xml
unzip ../source/sword_modules/en/KJV.zip -d tmp/ && mod2osis KJV > tmp/KJV.xml
unzip ../source/sword_modules/en/KJVA.zip -d tmp/ && mod2osis KJVA > tmp/KJVA.xml
unzip ../source/sword_modules/en/KJVPCE.zip -d tmp/ && mod2osis KJVPCE > tmp/KJVPCE.xml
unzip ../source/sword_modules/en/LEB.zip -d tmp/ && mod2osis LEB > tmp/LEB.xml
unzip ../source/sword_modules/en/LITV.zip -d tmp/ && mod2osis LITV > tmp/LITV.xml
unzip ../source/sword_modules/en/LO.zip -d tmp/ && mod2osis LO > tmp/LO.xml
unzip ../source/sword_modules/en/Leeser.zip -d tmp/ && mod2osis Leeser > tmp/Leeser.xml
unzip ../source/sword_modules/en/MKJV.zip -d tmp/ && mod2osis MKJV > tmp/MKJV.xml
unzip ../source/sword_modules/en/Montgomery.zip -d tmp/ && mod2osis Montgomery > tmp/Montgomery.xml
unzip ../source/sword_modules/en/Murdock.zip -d tmp/ && mod2osis Murdock > tmp/Murdock.xml
unzip ../source/sword_modules/en/NETfree.zip -d tmp/ && mod2osis NETfree > tmp/NETfree.xml
unzip ../source/sword_modules/en/NETtext.zip -d tmp/ && mod2osis NETtext > tmp/NETtext.xml
unzip ../source/sword_modules/en/NHEB.zip -d tmp/ && mod2osis NHEB > tmp/NHEB.xml
unzip ../source/sword_modules/en/NHEBJE.zip -d tmp/ && mod2osis NHEBJE > tmp/NHEBJE.xml
unzip ../source/sword_modules/en/NHEBME.zip -d tmp/ && mod2osis NHEBME > tmp/NHEBME.xml
unzip ../source/sword_modules/en/Noyes.zip -d tmp/ && mod2osis Noyes > tmp/Noyes.xml
unzip ../source/sword_modules/en/OEB.zip -d tmp/ && mod2osis OEB > tmp/OEB.xml
unzip ../source/sword_modules/en/OEBcth.zip -d tmp/ && mod2osis OEBcth > tmp/OEBcth.xml
unzip ../source/sword_modules/en/OrthJBC.zip -d tmp/ && mod2osis OrthJBC > tmp/OrthJBC.xml
unzip ../source/sword_modules/en/RKJNT.zip -d tmp/ && mod2osis RKJNT > tmp/RKJNT.xml
unzip ../source/sword_modules/en/RNKJV.zip -d tmp/ && mod2osis RNKJV > tmp/RNKJV.xml
unzip ../source/sword_modules/en/RWebster.zip -d tmp/ && mod2osis RWebster > tmp/RWebster.xml
unzip ../source/sword_modules/en/Rotherham.zip -d tmp/ && mod2osis Rotherham > tmp/Rotherham.xml
unzip ../source/sword_modules/en/SPE.zip -d tmp/ && mod2osis SPE > tmp/SPE.xml
unzip ../source/sword_modules/en/Twenty.zip -d tmp/ && mod2osis Twenty > tmp/Twenty.xml
unzip ../source/sword_modules/en/Tyndale.zip -d tmp/ && mod2osis Tyndale > tmp/Tyndale.xml
unzip ../source/sword_modules/en/UKJV.zip -d tmp/ && mod2osis UKJV > tmp/UKJV.xml
unzip ../source/sword_modules/en/WEB.zip -d tmp/ && mod2osis WEB > tmp/WEB.xml
unzip ../source/sword_modules/en/WEBBE.zip -d tmp/ && mod2osis WEBBE > tmp/WEBBE.xml
unzip ../source/sword_modules/en/WEBME.zip -d tmp/ && mod2osis WEBME > tmp/WEBME.xml
unzip ../source/sword_modules/en/Webster.zip -d tmp/ && mod2osis Webster > tmp/Webster.xml
unzip ../source/sword_modules/en/Weymouth.zip -d tmp/ && mod2osis Weymouth > tmp/Weymouth.xml
unzip ../source/sword_modules/en/Worsley.zip -d tmp/ && mod2osis Worsley > tmp/Worsley.xml
unzip ../source/sword_modules/en/YLT.zip -d tmp/ && mod2osis YLT > tmp/YLT.xml
