#!/bin/bash

./generate_pages_from_osis.py AB tmp/AB.xml
./generate_pages_from_osis.py ABP tmp/ABP.xml
./generate_pages_from_osis.py ACV tmp/ACV.xml
./generate_pages_from_osis.py AKJV tmp/AKJV.xml
./generate_pages_from_osis.py ASV tmp/ASV.xml
./generate_pages_from_osis.py Anderson tmp/Anderson.xml
./generate_pages_from_osis.py BBE tmp/BBE.xml
./generate_pages_from_osis.py BWE tmp/BWE.xml
./generate_pages_from_osis.py CPDV tmp/CPDV.xml
./generate_pages_from_osis.py Common tmp/Common.xml
./generate_pages_from_osis.py DRC tmp/DRC.xml
./generate_pages_from_osis.py Darby tmp/Darby.xml
./generate_pages_from_osis.py EMTV tmp/EMTV.xml
./generate_pages_from_osis.py Etheridge tmp/Etheridge.xml
./generate_pages_from_osis.py Geneva1599 tmp/Geneva1599.xml
./generate_pages_from_osis.py Godbey tmp/Godbey.xml
./generate_pages_from_osis.py GodsWord tmp/GodsWord.xml
./generate_pages_from_osis.py ISV tmp/ISV.xml
./generate_pages_from_osis.py JPS tmp/JPS.xml
./generate_pages_from_osis.py Jubilee2000 tmp/Jubilee2000.xml
./generate_pages_from_osis.py KJV tmp/KJV.xml
./generate_pages_from_osis.py KJVA tmp/KJVA.xml
./generate_pages_from_osis.py KJVPCE tmp/KJVPCE.xml
./generate_pages_from_osis.py LEB tmp/LEB.xml
./generate_pages_from_osis.py LITV tmp/LITV.xml
./generate_pages_from_osis.py LO tmp/LO.xml
./generate_pages_from_osis.py Leeser tmp/Leeser.xml
./generate_pages_from_osis.py MKJV tmp/MKJV.xml
./generate_pages_from_osis.py Montgomery tmp/Montgomery.xml
./generate_pages_from_osis.py Murdock tmp/Murdock.xml
./generate_pages_from_osis.py NETfree tmp/NETfree.xml
./generate_pages_from_osis.py NETtext tmp/NETtext.xml
./generate_pages_from_osis.py NHEB tmp/NHEB.xml
./generate_pages_from_osis.py NHEBJE tmp/NHEBJE.xml
./generate_pages_from_osis.py NHEBME tmp/NHEBME.xml
./generate_pages_from_osis.py Noyes tmp/Noyes.xml
./generate_pages_from_osis.py OEB tmp/OEB.xml
./generate_pages_from_osis.py OEBcth tmp/OEBcth.xml
./generate_pages_from_osis.py OrthJBC tmp/OrthJBC.xml
./generate_pages_from_osis.py RKJNT tmp/RKJNT.xml
./generate_pages_from_osis.py RNKJV tmp/RNKJV.xml
./generate_pages_from_osis.py RWebster tmp/RWebster.xml
./generate_pages_from_osis.py Rotherham tmp/Rotherham.xml
./generate_pages_from_osis.py SPE tmp/SPE.xml
./generate_pages_from_osis.py Twenty tmp/Twenty.xml
./generate_pages_from_osis.py Tyndale tmp/Tyndale.xml
./generate_pages_from_osis.py UKJV tmp/UKJV.xml
./generate_pages_from_osis.py WEB tmp/WEB.xml
./generate_pages_from_osis.py WEBBE tmp/WEBBE.xml
./generate_pages_from_osis.py WEBME tmp/WEBME.xml
./generate_pages_from_osis.py Webster tmp/Webster.xml
./generate_pages_from_osis.py Weymouth tmp/Weymouth.xml
./generate_pages_from_osis.py Worsley tmp/Worsley.xml
./generate_pages_from_osis.py YLT tmp/YLT.xml
